#!/bin/sh

check_suspend()
{
	grep -q mem /sys/power/state || [ -c /dev/pmu ]
}

do_suspend()
{
	if grep -q mem /sys/power/state; then
		echo -n "mem" > /sys/power/state
	elif [ -c /dev/pmu ]; then
		check_suspend_pmu && do_suspend_pmu
	fi
}

check_hibernate()
{
	[ -f /sys/power/disk ] && grep -q disk /sys/power/state
}

do_hibernate()
{
	[ -n "${HIBERNATE_MODE}" ] && \
	grep -qw "${HIBERNATE_MODE}" /sys/power/disk && \
	echo -n "${HIBERNATE_MODE}" > /sys/power/disk
	echo -n "disk" > /sys/power/state
}

check_suspend_hybrid()
{
	return 1
}

do_suspend_hybrid()
{
	return 1
}
