#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q '^ *version'; then
	pycentral pkgprepare python-textile <<PYEOF
[python-package]
format = 1
python-version = all
[pycentral]
version = 0.6.7
[files]
/usr/share/pyshared/textile.py=f
/usr/share/pyshared/textile-2.0.10.egg-info=f
PYEOF
else
	mkdir -p /var/lib/pycentral
	echo python-textile >> /var/lib/pycentral/delayed-pkgs
fi
# End automatically added section
