#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q '^ *version'; then
	pycentral pkgprepare python-twisted-lore <<PYEOF
[python-package]
format = 1
python-version = all
[pycentral]
version = 0.6.7
[files]
/usr/share/pyshared/twisted=d
/usr/share/pyshared/twisted/plugins=d
/usr/share/pyshared/twisted/plugins/twisted_lore.py=f
/usr/share/pyshared/twisted/lore=d
/usr/share/pyshared/twisted/lore/test=d
/usr/share/pyshared/twisted/lore/test/__init__.py=f
/usr/share/pyshared/twisted/lore/test/test_lore.py=f
/usr/share/pyshared/twisted/lore/test/test_man2lore.py=f
/usr/share/pyshared/twisted/lore/test/simple1.xhtml=f
/usr/share/pyshared/twisted/lore/test/simple3.html=f
/usr/share/pyshared/twisted/lore/test/simple4.html=f
/usr/share/pyshared/twisted/lore/test/good_internal.xhtml=f
/usr/share/pyshared/twisted/lore/test/simple.xhtml=f
/usr/share/pyshared/twisted/lore/test/lore_index_file_unnumbered_multiple_out.html=f
/usr/share/pyshared/twisted/lore/test/lore_index_file_out.html=f
/usr/share/pyshared/twisted/lore/test/lore_index_test_out.html=f
/usr/share/pyshared/twisted/lore/test/lore_index_test.xhtml=f
/usr/share/pyshared/twisted/lore/test/lore_numbering_test_out2.html=f
/usr/share/pyshared/twisted/lore/test/simple.html=f
/usr/share/pyshared/twisted/lore/test/lore_index_file_out_multiple.html=f
/usr/share/pyshared/twisted/lore/test/good_simple.xhtml=f
/usr/share/pyshared/twisted/lore/test/lore_numbering_test_out.html=f
/usr/share/pyshared/twisted/lore/test/lore_numbering_test.xhtml=f
/usr/share/pyshared/twisted/lore/test/lore_index_test_out2.html=f
/usr/share/pyshared/twisted/lore/test/lore_index_test2.xhtml=f
/usr/share/pyshared/twisted/lore/test/lore_index_test3.xhtml=f
/usr/share/pyshared/twisted/lore/test/simple2.xhtml=f
/usr/share/pyshared/twisted/lore/test/simple3.xhtml=f
/usr/share/pyshared/twisted/lore/test/lore_index_file_unnumbered_out.html=f
/usr/share/pyshared/twisted/lore/test/simple4.xhtml=f
/usr/share/pyshared/twisted/lore/test/template.tpl=f
/usr/share/pyshared/twisted/lore/test/simple4foo.xhtml=f
/usr/share/pyshared/twisted/lore/scripts=d
/usr/share/pyshared/twisted/lore/scripts/__init__.py=f
/usr/share/pyshared/twisted/lore/scripts/lore.py=f
/usr/share/pyshared/twisted/lore/indexer.py=f
/usr/share/pyshared/twisted/lore/__init__.py=f
/usr/share/pyshared/twisted/lore/tree.py=f
/usr/share/pyshared/twisted/lore/lmath.py=f
/usr/share/pyshared/twisted/lore/process.py=f
/usr/share/pyshared/twisted/lore/lint.py=f
/usr/share/pyshared/twisted/lore/texi.py=f
/usr/share/pyshared/twisted/lore/latex.py=f
/usr/share/pyshared/twisted/lore/htmlbook.py=f
/usr/share/pyshared/twisted/lore/man2lore.py=f
/usr/share/pyshared/twisted/lore/numberer.py=f
/usr/share/pyshared/twisted/lore/docbook.py=f
/usr/share/pyshared/twisted/lore/nevowlore.py=f
/usr/share/pyshared/twisted/lore/slides.py=f
/usr/share/pyshared/twisted/lore/default.py=f
/usr/share/pyshared/twisted/lore/_version.py=f
/usr/share/pyshared/twisted/lore/template.mgp=f
/usr/share/pyshared/Twisted_Lore-8.1.0.egg-info=f
PYEOF
else
	mkdir -p /var/lib/pycentral
	echo python-twisted-lore >> /var/lib/pycentral/delayed-pkgs
fi
# End automatically added section
