#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q '^ *version'; then
	pycentral pkgprepare python-crypto <<PYEOF
[python-package]
format = 1
python-version = 2.4, 2.5
[pycentral]
version = 0.6.7
[files]
/usr/share/pyshared/Crypto=d
/usr/share/pyshared/Crypto/Protocol=d
/usr/share/pyshared/Crypto/Protocol/__init__.py=f
/usr/share/pyshared/Crypto/Protocol/Chaffing.py=f
/usr/share/pyshared/Crypto/Protocol/AllOrNothing.py=f
/usr/share/pyshared/Crypto/Util=d
/usr/share/pyshared/Crypto/Util/number.py=f
/usr/share/pyshared/Crypto/Util/RFC1751.py=f
/usr/share/pyshared/Crypto/Util/__init__.py=f
/usr/share/pyshared/Crypto/Util/test.py=f
/usr/share/pyshared/Crypto/Util/randpool.py=f
/usr/share/pyshared/Crypto/PublicKey=d
/usr/share/pyshared/Crypto/PublicKey/qNEW.py=f
/usr/share/pyshared/Crypto/PublicKey/DSA.py=f
/usr/share/pyshared/Crypto/PublicKey/ElGamal.py=f
/usr/share/pyshared/Crypto/PublicKey/__init__.py=f
/usr/share/pyshared/Crypto/PublicKey/RSA.py=f
/usr/share/pyshared/Crypto/PublicKey/pubkey.py=f
/usr/share/pyshared/Crypto/__init__.py=f
/usr/share/pyshared/Crypto/test.py=f
/usr/share/pyshared/Crypto/Hash=d
/usr/share/pyshared/Crypto/Hash/__init__.py=f
/usr/share/pyshared/Crypto/Hash/SHA.py=f
/usr/share/pyshared/Crypto/Hash/MD5.py=f
/usr/share/pyshared/Crypto/Hash/HMAC.py=f
/usr/share/pyshared/Crypto/Cipher=d
/usr/share/pyshared/Crypto/Cipher/__init__.py=f
/usr/share/pyshared/pycrypto-2.0.1.egg-info=f
/usr/lib/python2.4/site-packages/Crypto=d
/usr/lib/python2.4/site-packages/Crypto/PublicKey=d
/usr/lib/python2.4/site-packages/Crypto/PublicKey/_fastmath.so=f
/usr/lib/python2.4/site-packages/Crypto/Hash=d
/usr/lib/python2.4/site-packages/Crypto/Hash/SHA256.so=f
/usr/lib/python2.4/site-packages/Crypto/Hash/MD2.so=f
/usr/lib/python2.4/site-packages/Crypto/Hash/MD4.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher=d
/usr/lib/python2.4/site-packages/Crypto/Cipher/DES.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/ARC4.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/CAST.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/Blowfish.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/DES3.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/ARC2.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/XOR.so=f
/usr/lib/python2.4/site-packages/Crypto/Cipher/AES.so=f
/usr/lib/python2.5/site-packages/Crypto=d
/usr/lib/python2.5/site-packages/Crypto/PublicKey=d
/usr/lib/python2.5/site-packages/Crypto/PublicKey/_fastmath.so=f
/usr/lib/python2.5/site-packages/Crypto/Hash=d
/usr/lib/python2.5/site-packages/Crypto/Hash/SHA256.so=f
/usr/lib/python2.5/site-packages/Crypto/Hash/MD2.so=f
/usr/lib/python2.5/site-packages/Crypto/Hash/MD4.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher=d
/usr/lib/python2.5/site-packages/Crypto/Cipher/DES.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/ARC4.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/CAST.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/Blowfish.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/DES3.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/ARC2.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/XOR.so=f
/usr/lib/python2.5/site-packages/Crypto/Cipher/AES.so=f
PYEOF
else
	mkdir -p /var/lib/pycentral
	echo python-crypto >> /var/lib/pycentral/delayed-pkgs
fi
# End automatically added section
