#!/bin/sh
set -e
# Automatically added by dh_pycentral
if which pycentral >/dev/null 2>&1 && pycentral --help 2>/dev/null | grep -q '^ *version'; then
	pycentral pkgprepare python-roman <<PYEOF
[python-package]
format = 1
python-version = >= 2.3
[pycentral]
version = 0.6.7
[files]
/usr/share/pyshared/roman-1.4.egg-info=f
/usr/share/pyshared/roman.py=f
PYEOF
else
	mkdir -p /var/lib/pycentral
	echo python-roman >> /var/lib/pycentral/delayed-pkgs
fi
# End automatically added section
